spring:
  jpa:
    show-sql: false
    database: mysql
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        implicit_naming_strategy: com.cetian.base.configuration.db.CtImplicitNamingStrategyImpl
        hbm2ddl:
          auto:
  datasource:
    db1: 
      type: org.apache.tomcat.jdbc.pool.DataSource
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/db_psns_yn?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&verifyServerCertificate=false&useSSL=true
      username: root
      password: root

      
